version: '3.8'

services:
  marcus:
    build: .
    container_name: marcus-mcp-server
    environment:
      # Kanban provider selection (github, linear, or planka)
      - KANBAN_PROVIDER=${KANBAN_PROVIDER:-github}
      
      # GitHub configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      
      # Linear configuration (if using Linear)
      - LINEAR_API_KEY=${LINEAR_API_KEY}
      - LINEAR_TEAM_ID=${LINEAR_TEAM_ID}
      
      # Planka configuration (if using Planka)
      - PLANKA_PROJECT_NAME=${PLANKA_PROJECT_NAME}
      
      # AI configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Original config
      - MARCUS_CONFIG=/app/config/pm_agent_config.json
      - MARCUS_MONITORING_INTERVAL=900
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
      - ./prompts:/app/prompts
    command: python marcus_mcp_server.py
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - marcus-network

  # Development version with live code reload
  marcus-dev:
    build: .
    container_name: marcus-dev
    environment:
      # Kanban provider selection
      - KANBAN_PROVIDER=${KANBAN_PROVIDER:-github}
      
      # GitHub configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      
      # Linear configuration
      - LINEAR_API_KEY=${LINEAR_API_KEY}
      - LINEAR_TEAM_ID=${LINEAR_TEAM_ID}
      
      # Planka configuration
      - PLANKA_PROJECT_NAME=${PLANKA_PROJECT_NAME}
      
      # AI configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Original config
      - MARCUS_CONFIG=/app/config/pm_agent_config.json
      - MARCUS_MONITORING_INTERVAL=900
    volumes:
      # Mount source code for live updates
      - ./src:/app/src
      - ./marcus_mcp_server.py:/app/marcus_mcp_server.py
      - ./marcus.py:/app/marcus.py
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
      - ./prompts:/app/prompts
    command: python marcus_mcp_server.py
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - marcus-network
  
  # Visualization UI (optional)
  visualization:
    build:
      context: ./visualization-ui
      dockerfile: Dockerfile
    container_name: marcus-visualization
    ports:
      - "4298:4298"  # Vite dev server
      - "8080:8080"  # WebSocket server
    environment:
      - NODE_ENV=development
    volumes:
      - ./visualization-ui/src:/app/src
      - ./visualization-ui/public:/app/public
    networks:
      - marcus-network
    depends_on:
      - marcus
    profiles:
      - full  # Only start when --profile full is used
  
  # Demo workers for testing
  worker-backend:
    build: .
    container_name: marcus-worker-backend
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./examples:/app/examples
    command: ["python", "examples/mock_agents/mock_claude_worker.py", "--name", "backend-developer", "--role", "Backend Developer", "--skills", "python,api,database,backend"]
    networks:
      - marcus-network
    depends_on:
      - marcus
    profiles:
      - demo  # Only start when --profile demo is used
  
  worker-frontend:
    build: .
    container_name: marcus-worker-frontend
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./examples:/app/examples
    command: ["python", "examples/mock_agents/mock_claude_worker.py", "--name", "frontend-developer", "--role", "Frontend Developer", "--skills", "javascript,react,vue,css,frontend"]
    networks:
      - marcus-network
    depends_on:
      - marcus
    profiles:
      - demo
  
  worker-qa:
    build: .
    container_name: marcus-worker-qa
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./examples:/app/examples
    command: ["python", "examples/mock_agents/mock_claude_worker.py", "--name", "qa-engineer", "--role", "QA Engineer", "--skills", "testing,automation,qa,selenium"]
    networks:
      - marcus-network
    depends_on:
      - marcus
    profiles:
      - demo

  # ⚠️ PLANKA - LOCAL USE ONLY ⚠️
  # Due to AGPL license, only enable for personal/local use
  # Use --profile local-planka to enable
  planka:
    image: ghcr.io/plankanban/planka:latest
    container_name: marcus-planka
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - planka-data:/app/public/user-avatars
      - planka-data:/app/public/project-background-images
      - planka-data:/app/private/attachments
    ports:
      - "1337:1337"  # Only exposed on localhost
    environment:
      - BASE_URL=http://localhost:1337
      - DATABASE_URL=postgresql://planka:planka@planka-db/planka
      - SECRET_KEY=${PLANKA_SECRET_KEY:-notsecretkey}
    depends_on:
      - planka-db
    networks:
      - marcus-network
    profiles:
      - local-planka  # Must explicitly enable

  planka-db:
    image: postgres:14-alpine
    container_name: marcus-planka-db
    restart: unless-stopped
    volumes:
      - planka-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_USER=planka
      - POSTGRES_PASSWORD=planka
    networks:
      - marcus-network
    profiles:
      - local-planka  # Must explicitly enable

  # MCP Server for Claude Code integration
  marcus-mcp:
    build: .
    container_name: marcus-mcp-stdio
    environment:
      # Inherit all environment variables from main service
      - KANBAN_PROVIDER=${KANBAN_PROVIDER:-github}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - LINEAR_API_KEY=${LINEAR_API_KEY}
      - LINEAR_TEAM_ID=${LINEAR_TEAM_ID}
      - PLANKA_PROJECT_NAME=${PLANKA_PROJECT_NAME}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MARCUS_CONFIG=/app/config/pm_agent_config.json
      - MARCUS_MONITORING_INTERVAL=900
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
      - ./prompts:/app/prompts
    command: python marcus_mcp_server.py
    stdin_open: true
    tty: false  # Important: MCP uses stdio, not TTY
    networks:
      - marcus-network
    profiles:
      - mcp  # Only start when --profile mcp is used

networks:
  marcus-network:
    driver: bridge

volumes:
  planka-data:
  planka-db-data:
